[package]
name = "api"
version = "0.1.0"
edition = "2018"

[dependencies]
actix = "=0.10.0"
actix-cors = "=0.5.4"
actix-redis = "=0.9.2"
actix-service = "=2.0.0-beta.5"
actix-web = "=3.3.0"
redis-async = "=0.6.3"
serde = "=1.0.126"
